<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.buukle.agent</groupId>
        <artifactId>agent-sphere</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>agent-sphere-instance</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>agent-sphere-instance-domain</module>
        <module>agent-sphere-instance-exception</module>
        <module>agent-sphere-instance-dtvo</module>
        <module>agent-sphere-instance-spi</module>
        <module>agent-sphere-instance-repository</module>
        <module>agent-sphere-instance-service</module>
        <module>agent-sphere-instance-controller</module>
    </modules>
</project>
