package com.buukle.agent.resource.template;

/**
 * 资源模板默认内容（身份源未配置 resource_template 时使用）。
 */
public final class ResourceTemplates {

    public static final String DEFAULT = """
            [
  {"type":"model_provider","name":"DeepSeek","baseUrl":"https://api.deepseek.com"},
  {"type":"api_key","provider":"DeepSeek","alias":"default-key"},
  {"type":"model_route","provider":"DeepSeek","modelName":"deepseek-v4-flash","company":"deepseek","weight":100},
  {"type":"completions","name":"简历解析","description":"从简历信息提取结构化字段（Bole: resume_parse）","businessType":"resume_parse","route":"deepseek-v4-flash","config":"{\\"temperature\\": 0.1, \\"thinking\\": false}","promptSystem":"你是资深招聘顾问，从简历信息提取结构化字段。只输出 JSON，不要额外说明。","promptUser":"{{input}}","inputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"resumeText\\"],\\"properties\\":{\\"resumeText\\":{\\"type\\":\\"string\\",\\"description\\":\\"简历原始文本\\"},\\"candidateId\\":{\\"type\\":\\"integer\\",\\"description\\":\\"Bole 候选人 id\\"}}}","outputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"name\\",\\"summary\\"],\\"properties\\":{\\"name\\":{\\"type\\":\\"string\\"},\\"phone\\":{\\"type\\":\\"string\\"},\\"email\\":{\\"type\\":\\"string\\"},\\"gender\\":{\\"type\\":\\"string\\"},\\"age\\":{\\"type\\":\\"integer\\"},\\"education\\":{\\"type\\":\\"array\\",\\"items\\":{\\"type\\":\\"object\\",\\"properties\\":{\\"school\\":{\\"type\\":\\"string\\"},\\"degree\\":{\\"type\\":\\"string\\"},\\"major\\":{\\"type\\":\\"string\\"},\\"startDate\\":{\\"type\\":\\"string\\"},\\"endDate\\":{\\"type\\":\\"string\\"}}}},\\"workExperience\\":{\\"type\\":\\"array\\",\\"items\\":{\\"type\\":\\"object\\",\\"properties\\":{\\"company\\":{\\"type\\":\\"string\\"},\\"title\\":{\\"type\\":\\"string\\"},\\"startDate\\":{\\"type\\":\\"string\\"},\\"endDate\\":{\\"type\\":\\"string\\"},\\"description\\":{\\"type\\":\\"string\\"}}}},\\"skills\\":{\\"type\\":\\"array\\",\\"items\\":{\\"type\\":\\"string\\"}},\\"summary\\":{\\"type\\":\\"string\\"}}}"},
  {"type":"completions","name":"5 维匹配","description":"按技能/职位/行业/目标公司/年限 5 维评分（Bole: five_dim_match）","businessType":"five_dim_match","route":"deepseek-v4-flash","config":"{\\"temperature\\": 0.2, \\"thinking\\": false}","promptSystem":"你是资深猎头，请按 技能/职位/行业/目标公司/年限 5 维对候选人匹配度评分(0-100)。只输出 JSON。","promptUser":"{{input}}","inputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"candidateProfile\\",\\"jobRequirement\\"],\\"properties\\":{\\"candidateProfile\\":{\\"type\\":\\"object\\",\\"description\\":\\"候选人画像\\"},\\"jobRequirement\\":{\\"type\\":\\"object\\",\\"description\\":\\"职位要求\\"}}}","outputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"scores\\",\\"overall\\"],\\"properties\\":{\\"scores\\":{\\"type\\":\\"object\\",\\"properties\\":{\\"skill\\":{\\"type\\":\\"integer\\",\\"minimum\\":0,\\"maximum\\":100},\\"position\\":{\\"type\\":\\"integer\\",\\"minimum\\":0,\\"maximum\\":100},\\"industry\\":{\\"type\\":\\"integer\\",\\"minimum\\":0,\\"maximum\\":100},\\"targetCompany\\":{\\"type\\":\\"integer\\",\\"minimum\\":0,\\"maximum\\":100},\\"years\\":{\\"type\\":\\"integer\\",\\"minimum\\":0,\\"maximum\\":100}}},\\"overall\\":{\\"type\\":\\"integer\\",\\"minimum\\":0,\\"maximum\\":100},\\"comment\\":{\\"type\\":\\"string\\"}}}"},
  {"type":"completions","name":"AI 触达话术","description":"生成面向候选人的暖场触达话术（Bole: outreach）","businessType":"outreach","route":"deepseek-v4-flash","config":"{\\"temperature\\": 0.7, \\"thinking\\": false}","promptSystem":"你是招聘顾问，为候选人生成自然真诚的暖场触达话术。只输出 JSON。","promptUser":"{{input}}","inputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"candidate\\"],\\"properties\\":{\\"candidate\\":{\\"type\\":\\"object\\",\\"description\\":\\"候选人信息\\"},\\"job\\":{\\"type\\":\\"object\\",\\"description\\":\\"职位信息\\"},\\"channel\\":{\\"type\\":\\"string\\",\\"description\\":\\"触达渠道，如 wechat/email\\"}}}","outputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"message\\"],\\"properties\\":{\\"message\\":{\\"type\\":\\"string\\",\\"description\\":\\"触达话术文案\\"}}}"},
  {"type":"completions","name":"自然语言搜索","description":"将自然语言寻访需求解析为结构化筛选条件（Bole: nl_search）","businessType":"nl_search","route":"deepseek-v4-flash","config":"{\\"temperature\\": 0.1, \\"thinking\\": false}","promptSystem":"你将自然语言寻访需求解析为结构化筛选条件(industry/skills/city/education/minYears/maxYears/minSalary/summary)。只输出 JSON。","promptUser":"{{input}}","inputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"query\\"],\\"properties\\":{\\"query\\":{\\"type\\":\\"string\\",\\"description\\":\\"自然语言寻访需求\\"}}}","outputSchema":"{\\"type\\":\\"object\\",\\"properties\\":{\\"industry\\":{\\"type\\":\\"string\\"},\\"skills\\":{\\"type\\":\\"array\\",\\"items\\":{\\"type\\":\\"string\\"}},\\"city\\":{\\"type\\":\\"string\\"},\\"education\\":{\\"type\\":\\"string\\"},\\"minYears\\":{\\"type\\":\\"integer\\"},\\"maxYears\\":{\\"type\\":\\"integer\\"},\\"minSalary\\":{\\"type\\":\\"integer\\"},\\"summary\\":{\\"type\\":\\"string\\"}}}"},
  {"type":"completions","name":"组织收集","description":"根据目标公司整理组织架构与联系信息（Bole: org_collect）","businessType":"org_collect","route":"deepseek-v4-flash","config":"{\\"temperature\\": 0.1, \\"thinking\\": false}","promptSystem":"你根据目标公司整理组织架构与联系信息。只输出 JSON。","promptUser":"{{input}}","inputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"company\\"],\\"properties\\":{\\"company\\":{\\"type\\":\\"string\\",\\"description\\":\\"目标公司名称\\"},\\"depth\\":{\\"type\\":\\"integer\\",\\"description\\":\\"收集层级深度\\"}}}","outputSchema":"{\\"type\\":\\"object\\",\\"properties\\":{\\"departments\\":{\\"type\\":\\"array\\",\\"items\\":{\\"type\\":\\"object\\",\\"properties\\":{\\"name\\":{\\"type\\":\\"string\\"},\\"manager\\":{\\"type\\":\\"string\\"},\\"contact\\":{\\"type\\":\\"string\\"}}}},\\"note\\":{\\"type\\":\\"string\\"}}}"},
  {"type":"completions","name":"评估报告推荐理由","description":"面向客户生成推荐理由（Bole: recommend_reason）","businessType":"recommend_reason","route":"deepseek-v4-flash","config":"{\\"temperature\\": 0.3, \\"thinking\\": false}","promptSystem":"你面向客户生成候选人推荐理由，突出亮点并提示风险。只输出 JSON。","promptUser":"{{input}}","inputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"candidate\\",\\"position\\"],\\"properties\\":{\\"candidate\\":{\\"type\\":\\"object\\",\\"description\\":\\"候选人画像\\"},\\"position\\":{\\"type\\":\\"object\\",\\"description\\":\\"职位要求\\"},\\"customer\\":{\\"type\\":\\"object\\",\\"description\\":\\"客户信息\\"}}}","outputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"reason\\"],\\"properties\\":{\\"reason\\":{\\"type\\":\\"string\\"},\\"highlights\\":{\\"type\\":\\"array\\",\\"items\\":{\\"type\\":\\"string\\"}},\\"risks\\":{\\"type\\":\\"array\\",\\"items\\":{\\"type\\":\\"string\\"}}}}"},
  {"type":"completions","name":"AI 面试题","description":"按岗位画像与简历差距生成面试题（Bole: interview_questions）","businessType":"interview_questions","route":"deepseek-v4-flash","config":"{\\"temperature\\": 0.6, \\"thinking\\": false}","promptSystem":"你根据岗位画像与候选人简历差距生成面试题(questions:[{dimension,type,content}])。只输出 JSON。","promptUser":"{{input}}","inputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"jobProfile\\",\\"resume\\"],\\"properties\\":{\\"jobProfile\\":{\\"type\\":\\"object\\",\\"description\\":\\"岗位画像\\"},\\"resume\\":{\\"type\\":\\"object\\",\\"description\\":\\"候选人简历\\"}}}","outputSchema":"{\\"type\\":\\"object\\",\\"required\\":[\\"questions\\"],\\"properties\\":{\\"questions\\":{\\"type\\":\\"array\\",\\"items\\":{\\"type\\":\\"object\\",\\"properties\\":{\\"dimension\\":{\\"type\\":\\"string\\"},\\"type\\":{\\"type\\":\\"string\\",\\"enum\\":[\\"behavioral\\",\\"technical\\",\\"situational\\"]},\\"content\\":{\\"type\\":\\"string\\"}}}}}}"},
  {"type":"instance","name":"Headhunter Assist","description":"Headhunter Assist","businessType":"task","route":"deepseek-v4-flash","systemPrompt":"You are Headhunter Assist, an automated assistant. Respond to the user's chat\\nquestions and use tools to help them achieve their goals.\\n\\nStrict rules:\\n- Only answer questions related to the Headhunter Assist business.\\n- When operating on websites in the browser, behave as naturally as a human\\n  would — interact with the site the way a real person does.\\n- Do not operate on the same website too frequently, to avoid triggering\\n  security mechanisms that could block our IP or account.\\n- While executing browser tasks, check your document list with the doc tool and\\n  reference the relevant experience documents.\\n- At the end of each task, summarize the experience gained during the process\\n  and create or update the experience document accordingly."},
  {"type":"mcp","name":"示例 MCP 服务","serverUrl":"http://localhost:8000/mcp","serverType":"stdio"},
  {"type":"skill","name":"示例技能","definition":"{\\"prompt\\":\\"请按配置执行\\"}"},
  {"type":"document","title":"AgentSphere 使用说明","content":"AgentSphere 能力开放说明：本身份源开通后已初始化默认资源（模型/能力/Completions/实例/文档）。请按需补充 API Key 与业务配置。"}
]
            """;

    private ResourceTemplates() {
    }
}
