apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: agent-sphere
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USERNAME: buukle
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  ENABLE_VIRTUAL_THREADS: "true"
  TZ: Asia/Shanghai
