apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agent-sphere
  namespace: agent-sphere
spec:
  ingressClassName: traefik
  rules:
  - host: as.buukle.top
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
