package com.buukle.agent.agui.dtvo;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum AguiEventType {
    RUN_STARTED("RUN_STARTED"),
    RUN_MESSAGE("RUN_MESSAGE"),
    RUN_ERROR("RUN_ERROR"),
    RUN_FINISHED("RUN_FINISHED"),
    STEP_STARTED("STEP_STARTED"),
    STEP_FINISHED("STEP_FINISHED"),
    TEXT_MESSAGE_START("TEXT_MESSAGE_START"),
    TEXT_MESSAGE_CONTENT("TEXT_MESSAGE_CONTENT"),
    TEXT_MESSAGE_END("TEXT_MESSAGE_END"),
    REASONING_MESSAGE_START("REASONING_MESSAGE_START"),
    REASONING_MESSAGE_CONTENT("REASONING_MESSAGE_CONTENT"),
    REASONING_MESSAGE_END("REASONING_MESSAGE_END"),
    TOOL_CALL_START("TOOL_CALL_START"),
    TOOL_CALL_ARGS("TOOL_CALL_ARGS"),
    TOOL_CALL_END("TOOL_CALL_END"),
    TOOL_CALL_RESULT("TOOL_CALL_RESULT"),
    STATE_SNAPSHOT("STATE_SNAPSHOT"),
    CUSTOM("CUSTOM");

    private final String value;
}