package com.buukle.agent.instance.dtvo.vo;

import lombok.Data;
import java.io.Serializable;

@Data
public class SessionVO implements Serializable {
    private Long id;
    private String title;
    private Long agentInstanceId;
    private String status;
    private String summary;
    private String summaryUpdatedAt;
    private Long summaryModelRouteId;
    private Boolean titleAutoGenerated;
    private String createdAt;
    private String createdBy;
    private String updatedBy;
    private String updatedAt;
}
