<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.buukle.agent</groupId>
        <artifactId>agent-sphere</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <artifactId>agent-sphere-capability-builtin</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>agent-sphere-capability-builtin-dtvo</module>
        <module>agent-sphere-capability-builtin-spi</module>
        <module>agent-sphere-capability-builtin-service</module>
        <module>agent-sphere-capability-builtin-controller</module>
        <module>agent-sphere-capability-builtin-tool</module>
    </modules>
</project>
