package com.buukle.agent.instance.domain;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@TableName("agent_session")
public class AgentSession {
    @TableId(type = IdType.AUTO)
    private Long id;
    private String title;
    private Long agentInstanceId;
    private String contextData;
    @TableField("cached_in_redis")
    private Boolean cachedInRedis;
    private String status;
    private String summary;
    private LocalDateTime summaryUpdatedAt;
    private Long summaryModelRouteId;
    @TableField("title_auto_generated")
    private Boolean titleAutoGenerated;
    @TableLogic
    private Boolean deleteFlag;
    private Long tenantId;
    @TableField(fill = FieldFill.INSERT)
    private String createdBy;
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private String updatedBy;
    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createdAt;
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updatedAt;
}
